Update helper tools

diff --git a/bin/adjust-app-volume b/bin/adjust-app-volume
--- a/bin/adjust-app-volume
+++ b/bin/adjust-app-volume
@@ -7,54 +7,29 @@ if [ $# != 2 ]; then
     exit 1
 fi
 
-getappmuted() {
-    return "$(
-    pacmd list-sink-inputs | \
-        gawk 'BEGIN {sinkindexid = -1; foundsink = 0; }
-             /^$/ {sinkindexid = -1; foundsink = 0; }
-             /^\s+index:\s/ {sinkindexid = $2; }
-             /^\s+client:\s/ && (sinkindexid >= 0) && ($2 == "\"'"$1"'\"" ) {foundsink = 1 }
-             /^\s+muted:\s/ && (sinkindexid >= 0) && ( $2 == "yes" ) && (foundsink == 1) { print 1 ; exit}
-             /^\s+muted:\s/ && (sinkindexid >= 0) && ( $2 == "no" ) && (foundsink == 1) { print 0 ; exit}'
-             )" || return 0 # fallback
-}
-
 getappvol() {
-    pacmd list-sink-inputs | \
-        gawk 'BEGIN {sinkindexid = -1; inproperties = 0; clientid = -1; lastlinevolume = 0; volumeline = "" }
-             /^$/ { sinkindexid = -1; inproperties = 0; clientid = -1; }
-             !/:/ && ( lastlinevolume > 0 ) { volumeline = volumeline " " $0 }
-             /:/ { lastlinevolume = 0; }
-             /^\s+index:\s/ {sinkindexid = $2; inproperties = 0;}
-             /^\s+client:\s/ && (sinkindexid > 0) {clientid = $2 }
-             /^\s+volume:/ && (sinkindexid > 0) {lastlinevolume = 1; volumeline = $0;}
-             /^\s+properties:\s*$/ && (inproperties == 0 ) && (sinkindexid > 0) {inproperties = 1 }
-             /^\s+application\.process\.binary = / && (clientid >= 0) && (inproperties > 0) && ($3 ==  "\"'"$1"'\"") { print volumeline }' | cut -d : -f 2- | tr --squeeze-repeats ' ' \\n | grep -- '%$' | tr -d % | \
-                 gawk '{ total += ($1 / 100); count++ } END { print total/count }'
+  volume=''
+  volume_lines="$(
+    pw-dump | jq -r '.[] | select (.id='"$1"') | \
+        select (.info.props."media.class"=="Stream/Output/Audio") | .info.params.Props | .[] | select(.channelVolumes != null) | .channelVolumes | .[]'
+  )"
+  linecount="$( printf "%s\n" "$volume_lines" | wc -l )"
+  if [ "$linecount" -gt 0 ]; then
+    volume="$( printf "%s\n" "$volume_lines" | awk '{s+=$1} END {print (s / '"$linecount"')}' )"
+  fi
+  printf "%.0f" "$volume"
 }
 
 getappsinkid() {
-    pacmd list-sink-inputs | \
-        gawk 'BEGIN {sinkindexid = -1; inproperties = 0; clientid = -1; }
-             /^$/ {sinkindexid = -1; clientid = -1; inproperties = 0; }
-             /^\s+index:\s/ {sinkindexid = $2; inproperties = 0 }
-             /^\s+client:\s/ && (sinkindexid >= 0 ) {clientid = $2 }
-             /^\s+properties:\s*$/ && (inproperties == 0 ) && (clientid >= 0) {inproperties = 1 }
-             /^\s+application\.process\.binary\s=\s/ && (clientid >= 0) && (inproperties > 0) && ($3 ==  "\"'"$1"'\"") { print sinkindexid }'
+  pw-dump | jq -r '.[] | select (.info.props."application.name"=="'"$1"'") | select (.info.props."media.class"=="Stream/Output/Audio") | .id' | tr -d \\n
 }
 
 getappsinkname() {
-    pacmd list-sink-inputs | \
-        gawk 'BEGIN {sinkindexid = -1; inproperties = 0; }
-             /^$/ {sinkindexid = -1; inproperties = 0; }
-             /^\s+index:\s/ {sinkindexid = $2; inproperties = 0 }
-             /^\s+client:\s/ && (sinkindexid >= 0) {clientline = $0 }
-             /^\s+properties:/ && (inproperties == 0 ) && (sinkindexid >= 0) {inproperties = 1 }
-             /^\s+application\.process\.binary\s=\s/ && (sinkindexid >= 0) && (inproperties > 0) && ($3 ==  "\"'"$1"'\"") { print clientline }' | sed -e 's,^.* <,,' -e 's,>$,,'
+  pw-dump | jq -r '.[] | select (.id='"$1"') | select (.info.props."media.class"=="Stream/Output/Audio") | .info.props."node.name"' | tr -d \\n
 }
 
 if ! ( printf "%s" "$delta" | grep -qE '[+-][1-9][0-9]*%?$' ); then
-    printf "%s: Invalid volume change: %s\n" "$( basename $0 )" "$delta" 1>&2
+    printf "%s: Invalid volume change: %q\n" "$( basename $0 )" "$delta" 1>&2
     exit 1
 fi
 
@@ -62,7 +37,15 @@ if ! ( printf "%s" "$delta" | grep -qE '%$' ); then
     delta="${delta}%"
 fi
 
-pactl set-sink-input-volume "$( getappsinkid "$app" )" "$( printf "%s" "${delta}" )"
+appsinkid="$( getappsinkid "$app" )"
+if [ "$appsinkid" = "" ]; then
+    printf "%s: Invalid app: %q\n" "$( basename $0 )" "$app" 1>&2
+    exit 1
+fi
+
+new_volume="$( getappvol "$appsinkid" | awk '{ print $1 + '"$volume_change"' }' )"
+
+pw-cli s "$default_sink_id" Props "{ mute: false, channelVolumes: [ $new_volume , $new_volume ] }"
 
 icon=audio-volume-low-symbolic
 volume="$(getappvol "${app}" )"
@@ -75,7 +58,8 @@ fi
 if (( $(echo "${volume} > 1.0" |bc -l) )); then
     icon=audio-volume-overamplified-symbolic
 fi
-if (( $(echo "${volume} > 1.0" |bc -l) )); then
-    extratext=" ($( echo "${volume} * 100" |bc | cut -d . -f 1)%)"
-fi
-gdbus call --session --dest 'org.gnome.Shell' --object-path '/org/gnome/Shell' --method 'org.gnome.Shell.ShowOSD' "{'icon': <'${icon}'>, 'label': <'$(getappsinkname "${app}" ) volume${extratext}'>, 'level': <${volume}>}" > /dev/null
+percentage="$( echo "${volume} * 100" |bc | cut -d . -f 1)%"
+
+app_short="$( printf "%s" "$app" | tr A-Z a-z | tr ' ' _ )"
+
+notify-send "App volume change" "Set volume for ${app} to ${percentage}" --hint "string:image-path:${icon}" --transient
